// 33 MCI Triage & First Aid rules — verbatim from the source spec.
// DO NOT MODIFY rule logic. Categories used: "categories" array used for filtering.

export type TriageColor = "RED" | "YELLOW" | "GREEN" | "BLACK" | null;

export interface Rule {
  id: number;
  title: string;
  category: ("Adult" | "Pediatric" | "Consent" | "Safety" | "Trauma" | "Medical" | "Process")[];
  condition: string;
  action: string;
}

export const RULES: Rule[] = [
  { id: 1, title: "Walking Victim Rule", category: ["Adult","Pediatric"],
    condition: "IF the victim can walk",
    action: "THEN classify the victim as Green AND instruct the victim to move to a safe designated area." },
  { id: 2, title: "Walking but Wrong Area Rule", category: ["Adult","Pediatric"],
    condition: "IF the victim can walk but moves to the wrong area or shows signs of confusion",
    action: "THEN classify the victim as Yellow AND perform further assessment." },
  { id: 3, title: "Re-triage for Green Victim Rule", category: ["Process"],
    condition: "IF the victim was classified as Green but their condition becomes worse",
    action: "THEN restart the triage assessment from breathing status." },
  { id: 4, title: "Not Breathing Initial Rule", category: ["Adult","Pediatric"],
    condition: "IF the victim is not breathing",
    action: "THEN instruct the responder to open or reposition the airway." },
  { id: 5, title: "Breathing After Airway Rule", category: ["Adult"],
    condition: "IF the victim was not breathing but starts breathing after airway repositioning",
    action: "THEN classify the victim as Red AND recommend immediate treatment." },
  { id: 6, title: "Not Breathing After Airway Rule", category: ["Adult"],
    condition: "IF the victim is still not breathing after airway repositioning",
    action: "THEN classify the victim as Black AND do not prioritize resuscitation during mass casualty triage." },
  { id: 7, title: "Adult High Respiratory Rate Rule", category: ["Adult"],
    condition: "IF the victim is an adult AND breathing rate is more than 30 breaths per minute",
    action: "THEN classify the victim as Red AND recommend immediate treatment." },
  { id: 8, title: "Adult Normal Respiratory Rate Rule", category: ["Adult","Process"],
    condition: "IF the victim is an adult AND breathing rate is 30 breaths per minute or below",
    action: "THEN continue assessment by checking perfusion." },
  { id: 9, title: "Poor Perfusion Rule", category: ["Adult"],
    condition: "IF radial pulse is absent OR capillary refill time is more than 2 seconds",
    action: "THEN classify the victim as Red AND recommend circulation support or bleeding control." },
  { id: 10, title: "Good Perfusion Rule", category: ["Adult","Process"],
    condition: "IF radial pulse is present AND capillary refill time is 2 seconds or below",
    action: "THEN continue assessment by checking mental status." },
  { id: 11, title: "Cannot Follow Commands Rule", category: ["Adult"],
    condition: "IF the victim cannot follow simple commands",
    action: "THEN classify the victim as Red AND recommend immediate monitoring and treatment." },
  { id: 12, title: "Can Follow Commands Rule", category: ["Adult"],
    condition: "IF the victim can follow simple commands AND breathing is stable AND perfusion is adequate",
    action: "THEN classify the victim as Yellow AND recommend delayed treatment." },
  { id: 13, title: "Severe Bleeding Rule", category: ["Trauma"],
    condition: "IF the victim has severe bleeding",
    action: "THEN classify the victim as Red AND recommend direct pressure or tourniquet if appropriate and trained." },
  { id: 14, title: "Open Fracture Rule", category: ["Trauma"],
    condition: "IF bone is visible OR an open fracture is suspected",
    action: "THEN classify the injury as serious AND recommend covering the wound and splinting the injured area. IF there are no Red symptoms THEN classify the victim as Yellow." },
  { id: 15, title: "Burn Injury Rule", category: ["Trauma"],
    condition: "IF the victim has burns AND has breathing difficulty or airway involvement",
    action: "THEN classify the victim as Red. ELSE IF the burn is serious but breathing is stable THEN classify the victim as Yellow." },
  { id: 16, title: "Heat Stroke Rule", category: ["Medical"],
    condition: "IF the victim has high body temperature AND confusion, altered mental status, or collapse",
    action: "THEN classify the victim as Red AND recommend immediate cooling." },
  { id: 17, title: "Heat Exhaustion Rule", category: ["Medical"],
    condition: "IF the victim shows dehydration, tiredness, dizziness, or weakness AND is conscious and breathing normally",
    action: "THEN classify the victim as Yellow AND recommend rest, cooling, and monitoring." },
  { id: 18, title: "Stroke FAST Rule", category: ["Medical"],
    condition: "IF the victim shows Face drooping OR Arm weakness OR Speech difficulty",
    action: "THEN classify the victim as Red AND recommend urgent transport or medical attention." },
  { id: 19, title: "Heart Attack Rule", category: ["Medical"],
    condition: "IF the victim has chest pain AND pain radiates to the arm, jaw, back, or shoulder",
    action: "THEN classify the victim as Red AND recommend urgent medical attention." },
  { id: 20, title: "Seizure Rule", category: ["Medical"],
    condition: "IF the victim is having uncontrolled body movements or seizure activity",
    action: "THEN classify the victim as Red during active seizure AND recommend protecting the victim from surrounding hazards." },
  { id: 21, title: "Anaphylaxis Rule", category: ["Medical"],
    condition: "IF the victim has signs of severe allergic reaction AND has breathing difficulty, swelling, or collapse",
    action: "THEN classify the victim as Red AND recommend urgent medical attention." },
  { id: 22, title: "Pediatric Breathing Rate Rule", category: ["Pediatric"],
    condition: "IF the victim is a child AND respiratory rate is less than 15 breaths per minute OR more than 45 breaths per minute",
    action: "THEN classify the victim as Red." },
  { id: 23, title: "Pediatric Normal Breathing Rule", category: ["Pediatric","Process"],
    condition: "IF the victim is a child AND respiratory rate is between 15 and 45 breaths per minute",
    action: "THEN continue assessment using circulation and AVPU mental status." },
  { id: 24, title: "Pediatric Not Breathing With Pulse Rule", category: ["Pediatric"],
    condition: "IF the victim is a child AND is not breathing AND has a pulse",
    action: "THEN recommend 5 rescue breaths." },
  { id: 25, title: "Pediatric Starts Breathing After Rescue Breaths Rule", category: ["Pediatric"],
    condition: "IF the victim is a child AND starts breathing after 5 rescue breaths",
    action: "THEN classify the victim as Red." },
  { id: 26, title: "Pediatric Still Not Breathing Rule", category: ["Pediatric"],
    condition: "IF the victim is a child AND still does not breathe after rescue breaths",
    action: "THEN classify the victim as Black." },
  { id: 27, title: "Pediatric AVPU Rule", category: ["Pediatric"],
    condition: "IF the victim is a child AND AVPU result is Unresponsive OR shows inappropriate response to Voice or Pain",
    action: "THEN classify the victim as Red." },
  { id: 28, title: "Conflict Resolution Rule", category: ["Process"],
    condition: "IF the victim satisfies more than one triage category",
    action: "THEN select the most severe category. Priority: Red > Yellow > Green. Black only when not breathing after airway or rescue-breath rules." },
  { id: 29, title: "Re-triage Rule", category: ["Process"],
    condition: "IF a victim has already been classified AND their breathing, circulation, or mental status changes",
    action: "THEN re-run the full triage process." },
  { id: 30, title: "Consent Rule", category: ["Consent"],
    condition: "IF the victim is conscious AND refuses to be touched or treated",
    action: "THEN do not perform physical treatment AND record refusal if possible." },
  { id: 31, title: "Implied Consent Rule", category: ["Consent"],
    condition: "IF the victim is unconscious",
    action: "THEN assume implied consent AND continue assessment within the responder's training level." },
  { id: 32, title: "Scene Safety Rule", category: ["Safety"],
    condition: "IF the environment is unsafe",
    action: "THEN do not enter the danger area AND wait for proper safety support or emergency services." },
  { id: 33, title: "METHANE Reporting Rule", category: ["Process","Safety"],
    condition: "IF a mass casualty incident is confirmed",
    action: "THEN prepare report using METHANE: Major incident declared, Exact location, Type of incident, Hazards present, Access routes, Number/severity of casualties, Emergency services required or present." },
];
